Add files via upload

diff --git a/polacz_pliki b/polacz_pliki
--- a/polacz_pliki
+++ b/polacz_pliki
@@ -6,42 +6,44 @@ file=`tput setaf 4`
 reset=`tput sgr 0`
 
 success=0
-
-for (( i = 2; i <= $# ; i++)); do
-		plik=${!i}
-		#sprawdzenie czy plik istnieje
-		if [ -e $plik ]; then
-			#sprawdzenie czy mamy prawa do odczytu
-			if [ -r $plik ]; then	
-				#sprawdzenie czy mamy prawa do zapisu #tego if'a wywalic na sam poczatek bo on ma sprawdzac czy mamy prawo do zapisu do $1
-				if [ -w $plik ]; then
-					#sprawdzenie czy plik nie jest pusty
-					if [ -s $plik ]; then
-						#sprawdzenie czy plik jest zwykły
-						if [ -f $plik ]; then
-							cat ${!i} >> $1
-							((success++))
-						else	
-							echo "${error}Plik: ${file}${!i} ${error}nie jest zwyklym plikiem${reset}"
-							exit 1
-						fi
+if [ ! -e $1 ]; then
+	echo "${green}Plik: ${file}$1 ${green}nie istnieje, wiec zostanie stworzony ${reset}"
+else
+	if [ ! -w $1 ]; then
+		echo "${error}Brak praw do zapisu do pliku: ${file}$1 ${reset}"
+		exit 1
+	else
+		for (( i = 2; i <= $# ; i++)); do
+				plik=${!i}
+				#sprawdzenie czy plik istnieje
+				if [ -e $plik ]; then
+					#sprawdzenie czy mamy prawa do odczytu
+						if [ -w $plik ]; then
+							#sprawdzenie czy plik nie jest pusty
+							if [ -s $plik ]; then
+								#sprawdzenie czy plik jest zwykły
+								if [ -f $plik ]; then
+									cat ${!i} >> $1
+									((success++))
+								else	
+									echo "${error}Plik: ${file}${!i} ${error}nie jest zwyklym plikiem${reset}"
+									exit 1
+								fi
+							else
+								echo "${error}Plik: ${file}${!i} ${error} jest pusty${reset}"
+								exit 1
+							fi
 					else
-						echo "${error}Plik: ${file}${!i} ${error} jest pusty${reset}"
+						echo "${error}Brak prawa do odczytu pliku: ${file}${!i}${reset}"
 						exit 1
 					fi
 				else
-					echo "${error}Brak prawa do zapisu pliku: ${file}${!i} ${reset}"
+					echo "${error}Plik ${file}${!i} ${error}nie istnieje${reset}"
 					exit 1
 				fi
-			else
-				echo "${error}Brak prawa do odczytu pliku: ${file}${!i}${reset}"
-				exit 1
-			fi
-		else
-			echo "${error}Plik ${file}${!i} ${error}nie istnieje${reset}"
-			exit 1
-		fi
-done
+		done
+	fi
+fi
 if [ $success -ge 1 -a $success -le 4 ];then
 	echo "${green}Udalo sie polaczyc $success pliki do pliku: ${file}$1${reset}"
 else
